//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrodUI.Assets.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrodUI.Assets.Languages.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Convert Image.
        /// </summary>
        public static string Convert_LabelButtonConvert {
            get {
                return ResourceManager.GetString("Convert_LabelButtonConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Image.
        /// </summary>
        public static string Convert_LabelButtonDeleteImage {
            get {
                return ResourceManager.GetString("Convert_LabelButtonDeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load Image file.
        /// </summary>
        public static string Convert_LabelButtonLoadImage {
            get {
                return ResourceManager.GetString("Convert_LabelButtonLoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Height.
        /// </summary>
        public static string Convert_LabelImageHeight {
            get {
                return ResourceManager.GetString("Convert_LabelImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Width.
        /// </summary>
        public static string Convert_LabelImageWidth {
            get {
                return ResourceManager.GetString("Convert_LabelImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Convert.
        /// </summary>
        public static string PageName_Convert {
            get {
                return ResourceManager.GetString("PageName_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export.
        /// </summary>
        public static string PageName_Export {
            get {
                return ResourceManager.GetString("PageName_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string PageName_Settings {
            get {
                return ResourceManager.GetString("PageName_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tutorial.
        /// </summary>
        public static string PageName_Tutorial {
            get {
                return ResourceManager.GetString("PageName_Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About BrodUI.
        /// </summary>
        public static string Settings_LabelAbout {
            get {
                return ResourceManager.GetString("Settings_LabelAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Links.
        /// </summary>
        public static string Settings_LabelGitHubLinks {
            get {
                return ResourceManager.GetString("Settings_LabelGitHubLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string Settings_LabelLanguage {
            get {
                return ResourceManager.GetString("Settings_LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminal.
        /// </summary>
        public static string Settings_LabelTerminal {
            get {
                return ResourceManager.GetString("Settings_LabelTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Theme.
        /// </summary>
        public static string Settings_LabelTheme {
            get {
                return ResourceManager.GetString("Settings_LabelTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Third party libraries.
        /// </summary>
        public static string Settings_LabelThirdPartyLibraries {
            get {
                return ResourceManager.GetString("Settings_LabelThirdPartyLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Latest release on GitHub.
        /// </summary>
        public static string Settings_LinkLatestReleaseOnGithub {
            get {
                return ResourceManager.GetString("Settings_LinkLatestReleaseOnGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project website on GitHub.
        /// </summary>
        public static string Settings_LinkProjectWebsiteOnGitHub {
            get {
                return ResourceManager.GetString("Settings_LinkProjectWebsiteOnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version 0.1.
        /// </summary>
        public static string Settings_VersionNumber {
            get {
                return ResourceManager.GetString("Settings_VersionNumber", resourceCulture);
            }
        }
    }
}
